FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install build-essential python3.6 python3.6-dev python3-pip libssl-dev git

WORKDIR /home/elastalert

COPY ./ ./
RUN pip3 install -r requirements-dev.txt
RUN apt-get update && apt-get install -f python3-pip
RUN   python3.6 -m pip install elastalert
RUN   python3.6 -m pip install "setuptools>=11.3"
RUN   python3.6 setup.py install
RUN   python3.6 -m pip install "elasticsearch>=5.0.0"
RUN   elastalert-create-index
#RUN   elastalert-test-rule example_rules/example_frequency.yaml
CMD bash

